### ISSUE TITLE
(UI improvement) Remove borders from Google Docs-generated Home Page

### ISSUE THREAD

**Issue by ekafyi** [kawalcovid19/wargabantuwarga.com#118]
## Description

Remove borders from Google Docs-generated "tables" in Home Page UI and replace it with more visually pleasing separator.

from:
![Screen Shot 2021-07-17 at 22 50 47](https://user-images.githubusercontent.com/6597211/126042588-59a1ad9c-acda-4f90-8b3a-b95991053d22.png)

to:
![Screen Shot 2021-07-17 at 22 50 35](https://user-images.githubusercontent.com/6597211/126042580-c4dd8bc9-8556-4c13-8beb-6a2dab19f992.png)

## Implementation Model

Apply custom styling.

Ready to submit PR if approved.

**Comment by zainfathoni** [comment]
Approved! 💯 
I have also tracked it under #31 epic. Thanks @ekafyi !

**Comment by zainfathoni** [comment]
Btw, instead of creating your own PR, could you please do it on top of my `feature/typography` branch in #114 PR? Because I updated the styling of that home page and remove all the default styling from Google Docs.

You should be able to push your commits to that branch since you're a maintainer of this repository now. 😁

**Comment by zainfathoni** [comment]
If you need the Google Docs edit access to update its semantic elements so it matches with our new styling, please let me know @ekafyi.

I can request the access for you, thanks!
