### ISSUE TITLE
Serve database structure from on the wargabantuwarga.com static files infrastructure instead of merely linking to the Google Spreadsheets files

### ISSUE THREAD

**Issue by baraeb92** [kawalcovid19/wargabantuwarga.com#17]
## Description

Currently, the data that we presented on the wargabantuwarga.com is fetched directly from Google Docs and Google Suite infrastructure, which might limit the performance and access when accessed nationwide. 

## Implementation Model

Perhaps use cache feature, to allow us to fetch the cached data from our server, of which we call the Google Suite server only once per 15 minutes. That way we don't have to call the GSuite every time the user is visiting the web.

## Current Tasks

- [x] #33 
- [x] #34
- [x] #69 
- [x] #72
- [x] #76
- [x] #63
- [x] #89
- [x] #86
- [x] #87

**Comment by zainfathoni** [comment]
> Perhaps use cache feature, to allow us to fetch the cached data from our server, of which we call the Google Suite server only once per 15 minutes. That way we don't have to call the GSuite every time the user is visiting the web.

Our current implementation is already like that, but it's limited only to that [one particular document](https://kcov.id/wbw-docs). We need to expand this implementation into the other documents, especially the Google Sheets file since we don't have any implementation for it yet.

@adityapurwa would you like to work on it?

**Comment by zainfathoni** [comment]
All items are completed. Further improvements will be recorded under #110 epic.
