### ISSUE TITLE
Refactor use-search to use a properly-typed fuzzy-search library

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#197]
## Brief

The current `useSearch()` implementation uses the `itemsjs` library, which has no proper typings. This leads to `useSearch()` being littered with `any` type annotations.

We want to avoid using `any` if possible. Therefore, we should migrate to a search library with proper typings (e.g. [fusejs](https://fusejs.io/)).

## Definition of done

- `use-search` properly migrated to a library with valid typings.
- All `any` are replaced by correct typings.

## Tasks

- [ ] Migrate to a properly typed fuzzy search library
- [ ] Refactor `use-search` to use fusejs and add proper typings

**Comment by resir014** [comment]
`useSearch()` also uses the `itemsjs` library, which has no proper typings.

Highly recommend switching to a properly typed library, e.g. [fusejs](https://fusejs.io/)

**Comment by resir014** [comment]
Issue + tasks list updated.

**Comment by mazipan** [comment]
## Itemsjs

https://bundlephobia.com/package/itemsjs@2.1.10

Size: 64kB
Minified: 20kB

## Fuse.js

https://bundlephobia.com/package/fuse.js@6.4.6

Size: 15kB
Minified: 5kB

But yes, this is a big refactor.
Since you will face many differences between this two libraries.

**Comment by mazipan** [comment]
Since this issue is classified as a hard. I think it's better if we introduce an automated testing first for this component before go on the refactoring part.

The hard part is you need to tackle all cases, testing it, make sure it's not breaking.

@resir014 @zainfathoni

**Comment by resir014** [comment]
Found more issues with `itemsjs`: turns out it's using a vulnerable version of lodash:

![image](https://user-images.githubusercontent.com/5663877/126996085-f2392f07-30e9-4a3e-8cb8-70dd7d86ba9b.png)

A quick peek through the bundle analyser shows that it's coming from `itemsjs`:

![image](https://user-images.githubusercontent.com/5663877/126996174-37a487a2-f42f-41f1-99a2-326bfc1606c8.png)

We **need to expedite** moving away from itemsjs. Should we proritise this issue, or should we wait until the Typesense experiment at #374 is complete? Or more importantly, which one of these takes **the least effort**?

cc: @zainfathoni @mazipan @ekamuktia @famasya

**Comment by famasya** [comment]
As my experience, integrating Typesense into React component itself isn't take too much effort (and properly typed). I think we should take a look at #401 first, since it's having some minor issues @resir014 .

cc @zainfathoni @mazipan @ekamuktia

**Comment by zainfathoni** [comment]
Closing this issue in favour of the #374.
