### ISSUE TITLE
Search Issue in FAQ page

### ISSUE THREAD

**Issue by hendrasan** [kawalcovid19/wargabantuwarga.com#203]
## Description

There's a minor bug in search in FAQ page. 

1. Type "isoman" then Search
2. Choose filter "PCR"
3. Change the keyword to "vaksin" then Search
4. No results found, the filter lists change to "Semua" and "Vaksinasi" and the active filter changes to "Vaksinasi"

## Expected Behaviour

In step 4, there should be results displayed

## Additional Information

I think in step 3, the filter submitted to the form is still "PCR", thus any keyword changes after that still searches for "PCR" filter even if the active filter indicator already changes to "Vaksinasi" (or "Semua" in the case of no filters found for the keyword). To solve the bug, the user can reload the page then try again, click the reset button, or manually change the filter in step 4 to trigger the filter change hook.

This might be a rather edge case, but I imagine there will be a few people who are searching for multiple unrelated keywords and might be confused of no results during their searching process, especially once the FAQ database grows larger.

**Comment by ekamuktia** [comment]
Seems like I got confused when deciding the rule and interaction.
Especially because the filter is applied right away after selected and keyword is applied when the button is clicked for `FAQ` and `Province` page

Also for the `reset` button, current rule is to reset all values (`keyword`, `filter` and `sort`) but the  reset button position is next to keyword input so user may think it will only reset the keyword.

Any suggestion to improve the search interaction is welcomed.

**Comment by mazipan** [comment]
I don't think we need to reset the `filter` and `sort`.

If they want to reset the filter, just change to "semua".
Sort can be "reset", they should pick one of them.

So the reset should be applied for the keyword only.

Even in my opinion, we don't need this reset button since the search will auto applied when user type any character.
If they want to reset, just clear the input.

**Comment by mazipan** [comment]
Also I don't think the sort is necessary here.

We should split the list based on two type:
- Verified
- Non-Verified

These two type of list should (by default) sorted alphabetically.

Except we have other factors, like sort by "Terdekat"

**Comment by mazipan** [comment]
This is become harder, since we are reuse the logic for FAQ and Province page.

**Comment by zainfathoni** [comment]
Nice catch Mas @hendrasan, thank you for reporting this! 🙏

**Comment by mazipan** [comment]
Preview for the fix:

https://deploy-preview-218--wargabantuwarga.netlify.app/faq?q=Vaksin&kategori_pertanyaan=Vaksinasi
