### ISSUE TITLE
Filter order in FAQ Page

### ISSUE THREAD

**Issue by ekamuktia** [kawalcovid19/wargabantuwarga.com#232]
## Description

For FAQ page, it's probably more natural to show `Kategori Pertanyaan` filter ordered based on how the FAQ items are shown rather than alphabetical order.
![image](https://user-images.githubusercontent.com/9606523/126358794-0cb6660c-08f1-41e0-be9f-95f37b18f7cb.png)

## Implementation Model

Since all category filters are always shown for FAQ page, rather then setting the `filterItems` value generated from `useSearch`, it can be set by getting category list from grouped `faq`

**Comment by ekamuktia** [comment]
@zainfathoni Please check if this is needed or alphabetical order just like now is okay

**Comment by zainfathoni** [comment]
I think the current one, the alphabetical order, is better because even if we make it ordered based on the actual order in the result section, there's no clear visual cue that they have some correlations.

Moreover, alphabetical order is usually easier to scan anyway.

Thanks for proposing this enhancement, Mbak @ekamuktia, but I'm closing this issue for now.
If it turns out that we need it this way, we can always reopen this issue in the future. 🙏
