### ISSUE TITLE
Associate Search Console w Analytics

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#447]
## Description

https://search.google.com/search-console/settings/associations?utm_source=sci&utm_medium=sci&utm_campaign=sci&resource_id=sc-domain:wargabantuwarga.com

**Comment by zainfathoni** [comment]
<img width="597" alt="Screenshot 2021-07-26 at 20 06 12" src="https://user-images.githubusercontent.com/6315466/126986036-89e1b048-467a-49f7-9dd8-16e859867fa1.png">

I can't do it because I don't own the GA property.
I think we need Mas @baraeb92's help with this, but he needs to "own" the search property by [verifying himself](https://support.google.com/webmasters/answer/7687615#zippy=%2Cadd-or-remove-owners).

**Comment by baraeb92** [comment]
Will do this tomorrow morning, because I need infra team to add the TXT to the DNS. @zainfathoni

**Comment by baraeb92** [comment]
Unfortunately, it cannot be done using GA4 at the moment, any specific reason as to why this is necessary? 

See: https://support.google.com/webmasters/thread/77936816/linking-search-console-to-ga4?hl=en

@zainfathoni @mazipan
