### ISSUE TITLE
typeface-inter deprecated

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#517]
## Description

As you can read here: https://www.npmjs.com/package/typeface-inter

![Screenshot_20210731-064929_Chrome](https://user-images.githubusercontent.com/7221389/127721666-c05ce7c2-2759-45ae-8a3e-03467f2be167.jpg)

`typeface-inter` state itself that they are now deprecated.

We need to think to migrate this package to the new one, the one that being recommended by the author.

Since it's not breaking the old apps, so no rush for us to migrate it.
It's a low priority.

**Comment by resir014** [comment]
@mazipan The reason we're using `typeface-inter` right now is that `@fontsource/inter`, for some reason, doesn't have italic styles, whereas `typeface-inter` does. This is because `@fontsource/inter` uses the version published by Google Fonts, which does not have italics: https://github.com/google/fonts/issues/2386

**Comment by mazipan** [comment]
Close for now.
