### ISSUE TITLE
Total count showing a wrong number when query param kebutuhan exist

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#581]
## Description

- Open: Homepage > Klik "Donor Plasma"
  -  Or, just visit: https://www.wargabantuwarga.com/provinces?kebutuhan=Donor%20plasma directly
- "DKI Jakarta" show **459 Entry**
- But when you click it, it only have **4** data for "Donor Plasma"

![Screenshot_20210807-185421_Chrome](https://user-images.githubusercontent.com/7221389/128599259-7bba278e-92e1-4852-9095-bca492f65212.jpg)

## Expected Behaviour

When have query param `? kebutuhan=`, we expect user will only search for certain data in the province list, even they can change the selection on the province detail.

So my expectation also it will show the count of spesific "kebutuhan"

## Additional Information

We can work the quick fix for this, but I still prefer if we work on #486 first to make it easier for us differentiate the page.

**Comment by nkristoporus** [comment]
Hi @mazipan, I have done a little bit of investigation on this particular issue. I found out that the issue is because this page is using unfiltered data from `~/data/wbw-sheets.json` which contains all information including Rumah Sakit, Donor Plasma, Ambulans, and others. I can do a quick fix to resolve the issue with the current query param, but if you want to wait for #486 that's fine as well. Let me know your thoughts on this.

**Comment by mazipan** [comment]
Yeah, we can do a quick fix for now.
It's a big task if we want to take a proper steps in the current situation.

**Comment by nkristoporus** [comment]
Yeah, I will work on this. Thanks :pray:
