### ISSUE TITLE
Address and Copy Button are too close

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#584]
## Description

Open: https://www.wargabantuwarga.com/provinces/dki-jakarta

The Address and the Copy Button are too close for some data.
I think we need to set more space between these two elements.

![Screenshot_20210808-130614_Chrome](https://user-images.githubusercontent.com/7221389/128622579-bb6f6de1-5eea-480b-bfd4-db8398255b51.jpg)

## Expected Behaviour

Have enough space between copy button and the address data

**Comment by fauzialz** [comment]
Hello, mas. Could I work on this ticket?

**Comment by zainfathoni** [comment]
Yes, please raise a draft pull request soon, @fauzialz, thanks! 🙏

**Comment by fauzialz** [comment]
Hallo mas @zainfathoni. I checked the code and it seems that the issue has been fixed by this change #571. The changes gave 0.5rem spacing on the copy button. I don't know if this is still a valid issue or not.

![image](https://user-images.githubusercontent.com/42629134/128632123-c3e1fb47-b73b-4add-9d18-a6f846ad5ffe.png)

**Comment by fauzialz** [comment]
I check the production app too. I think this issue is solved. cc: @mazipan

**Comment by mazipan** [comment]
Checking it...
Since I open it before the PR merged 😂

**Comment by mazipan** [comment]
Ah yes, I think this is going to `invalid` now
