### ISSUE TITLE
Complete all logos on About Page

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#627]
## Description

See on Figma https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=458%3A1634
Live on https://www.wargabantuwarga.com/tentang-kami

We have uncomplete Collaborators Logos.

![Screen Shot 2021-08-10 at 16 31 02](https://user-images.githubusercontent.com/7221389/128844003-a22197d2-0fc1-41e0-aa39-b79259fa36d0.png)

## Expected Behaviour

We have logo for all the data as we have in homepage

![Screen Shot 2021-08-10 at 16 33 23](https://user-images.githubusercontent.com/7221389/128844076-75b7e7ed-55d4-4df0-af6d-4d4f91308564.png)

## Unavailable Logos

- [ ] Baznas - https://baznas.go.id/
- [ ] pandemictalks - https://www.instagram.com/pandemictalks/
- [ ] https://www.instagram.com/laporcovid19/
- [ ] https://www.instagram.com/filantropiindonesia/
- [ ] https://twitter.com/BantuCovid
- [ ] https://hive.human-initiative.org/site/login
- [ ] https://narasi.tv/
- [ ] https://qiscus.io/en
- [ ] https://www.instagram.com/humanitarianforumindonesia/
- [ ] https://urundayacovid.com/
- [ ] https://trustmedis.com/
- [ ] https://sbmi.or.id/
- [ ] https://covid19.atmago.com/id
- [ ] https://semuamuridsemuaguru.id/
- [ ] https://instagram.com/iluniuipsi
- [ ] https://www.kgmedia.id/

## Netlify CMS 

The data can be submitted via CMS, the Image should uploaded to Cloudinary

https://www.wargabantuwarga.com/admin/#/collections/about_page/entries/collaborators_about_page

![Screen Shot 2021-08-10 at 16 44 44](https://user-images.githubusercontent.com/7221389/128845563-a32a7d14-d3c1-4776-8f78-be1ba1e7fe49.png)

Name: for alt text in image
Link URL: for link to website/twitter/instagram
Thumbnail Image: the Logo

**Comment by dekwahdimas** [comment]
Hi, can you please upload these logos to Netlify CMS? I don't have any access to it so I can't upload it myself. I may upload them to my private Cloudinary first but I don’t think I have to since wargabantuwarga already have its own account. Thank you. 

**Baznas**
![baznaz](https://user-images.githubusercontent.com/56619123/128877336-0ff01b0b-b180-414d-8b47-d35dc917d6c4.png)

**pandemictalks**
![pandemictalks](https://user-images.githubusercontent.com/56619123/128877491-64cc40ab-f0a9-413b-a6d1-7bb3f37b9080.jpg)

**laporcovid19**
![laporcovid19](https://user-images.githubusercontent.com/56619123/128877525-7003af46-66fc-4bc9-a0bd-3cccfb2ea2af.jpg)

**Filantropi Indonesia**
![filantropiindonesia](https://user-images.githubusercontent.com/56619123/128877540-e3a9b168-4fab-489c-8001-344347e3fb84.jpg)

**BantuCovid**
![bantucovid](https://user-images.githubusercontent.com/56619123/128877573-a76015ad-ba84-4724-983d-14be77f87f03.jpg)

**Human Initiative Volunteer Energy**
![hive](https://user-images.githubusercontent.com/56619123/128877618-d3ea79d4-31ab-43c4-aee5-6c32b2e8134a.png)

**Narasi.tv**
![narasitv](https://user-images.githubusercontent.com/56619123/128877632-6d2c00a7-60f2-44f2-9b91-d63bfbfc3c40.png)

**Qiscus**
![qisqus](https://user-images.githubusercontent.com/56619123/128877669-709325c8-3790-48af-b44a-a9666f9588fa.png)

**Humanitarian Forum Indonesia**
![humanitarianforumindonesia](https://user-images.githubusercontent.com/56619123/128878014-99511d57-dee5-4d99-8351-bb1bc143ada9.jpg)

**UrunDaya Covid**
![urundaya](https://user-images.githubusercontent.com/56619123/128878048-c04cecd8-d3fc-4bf2-be9f-955fae181e88.png)

**Trust Medis**
![trustmedis](https://user-images.githubusercontent.com/56619123/128877625-685583ef-aeb9-40ba-aa5c-7928464b93e8.png)

**SBMI**
![sbmi](https://user-images.githubusercontent.com/56619123/128878063-ee642467-806c-48fc-9a03-e7c52741b1df.jpg)

**AtmaGo**
![atmago](https://user-images.githubusercontent.com/56619123/128878083-9df3e199-78aa-43b1-bd34-9ef648ffc9c1.png)

**Semua Murid Semua Guru**
![semuamurid-semuaguru](https://user-images.githubusercontent.com/56619123/128878095-5e3f3263-0383-4f62-b169-95eb9c8655d9.png)

**Ikatan Alumni Psikologi UI**
![iluniuipsi](https://user-images.githubusercontent.com/56619123/128878138-4c0a2f5a-bf6d-4f3a-8c73-7b12ddaa7096.jpg)

**KG Media**
Logo Biru
![kgmedia-biru](https://user-images.githubusercontent.com/56619123/128878159-c00a0edb-3258-4d1a-aaa6-661073f68d59.png)

Logo Putih
![kgmedia-putih](https://user-images.githubusercontent.com/56619123/128878185-533fe849-55fe-4754-accd-17957865956b.png)

**Comment by mazipan** [comment]
@resir014 help to upload it, and provide the Cloudinary URL to me.
I will help to update from the CMS

**Comment by mazipan** [comment]
Bump help to upload it @resir014 @zainfathoni

**Comment by resir014** [comment]
Hi @dekwahdimas + @mazipan, please find attached the links to the uploaded images on Cloudinary.

### Collaborators
**Baznas**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780534/128877336-0ff01b0b-b180-414d-8b47-d35dc917d6c4_mtoaae.png

**pandemictalks**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780581/128877491-64cc40ab-f0a9-413b-a6d1-7bb3f37b9080_x9dvwq.jpg

**laporcovid19**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780608/128877525-7003af46-66fc-4bc9-a0bd-3cccfb2ea2af_uuzvhg.jpg

**Filantropi Indonesia**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780633/128877540-e3a9b168-4fab-489c-8001-344347e3fb84_kce5oc.jpg

**BantuCovid**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780652/128877573-a76015ad-ba84-4724-983d-14be77f87f03_wps4ps.jpg

**Human Initiative Volunteer Energy**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780713/128877618-d3ea79d4-31ab-43c4-aee5-6c32b2e8134a_fksi4l.png

**Narasi.tv**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780731/128877632-6d2c00a7-60f2-44f2-9b91-d63bfbfc3c40_ubqqie.png

**Qiscus**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780753/128877669-709325c8-3790-48af-b44a-a9666f9588fa_oc3flx.png

**Humanitarian Forum Indonesia**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780780/128878014-99511d57-dee5-4d99-8351-bb1bc143ada9_yqjg1x.jpg

**UrunDaya Covid**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780804/128878048-c04cecd8-d3fc-4bf2-be9f-955fae181e88_xeds4y.png

**Trust Medis**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780829/128877625-685583ef-aeb9-40ba-aa5c-7928464b93e8_r5qwhv.png

**SBMI**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780861/128878063-ee642467-806c-48fc-9a03-e7c52741b1df_ku0z7h.jpg

**AtmaGo**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780883/128878083-9df3e199-78aa-43b1-bd34-9ef648ffc9c1_lcxrot.png

**Semua Murid Semua Guru**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780905/128878095-5e3f3263-0383-4f62-b169-95eb9c8655d9_trzdyn.png

**Ikatan Alumni Psikologi UI**
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780922/128878138-4c0a2f5a-bf6d-4f3a-8c73-7b12ddaa7096_vtt58i.jpg

**KG Media**
Logo Biru
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780950/128878159-c00a0edb-3258-4d1a-aaa6-661073f68d59_htas02.png

Logo Putih
https://res.cloudinary.com/wargabantuwarga/image/upload/v1628780971/128878185-533fe849-55fe-4754-accd-17957865956b_j1igam.png

**Comment by mazipan** [comment]
@all-contributors please add @dekwahdimas for example and data
