### ISSUE TITLE
Credential to Netlify CMS and Cloudinary Dashboard

### ISSUE THREAD

**Issue by dekwahdimas** [kawalcovid19/wargabantuwarga.com#696]
I've been reading issues with documentation label on it and found out that most of them required an access to Netlify CMS or Cloudinary Dashboard if we want to solve those issues. Then, I found this gist. 

https://gist.github.com/ekafyi/1a86987c111a96976309c12f047d43a9

I tried to search Mas @zainfathoni to ask for credential but then I got stuck again because I'm not part of WBW Slack.

I'm not sure if I miss anything that lead me to this confusion or this question is already asked before but here's why I opened this issue.

## Description

Add a section on CONTRIBUTING.md and CONTRIBUTING_ID.md files about how to contribute besides the coding part. I'm trying to learn Next.js after knowing about this repository (and I'm sure others too) but I (or we?) don't want to mess the code this soon, lol. This section could explain if people who don't know about coding should contribute on the other task or not.

## Implementation Model

- [ ] Explain about who have Credential to Netlify CMS and Cloudinary Dashboard.
- [ ] Explain if anyone else could have the credential and how.
- [ ] Edit CONTRIBUTING.md and CONTRIBUTING_ID.md files.

Thank you.

**Comment by zainfathoni** [comment]
Sorry for the trouble, @dekwahdimas. 😅

## Short-term solution

You can request access to Netlify CMS from me, just provide me with your Gmail account, so you can log in using Google account.
Whereas for the Cloudinary Dashboard, since we're using the free tier with a shared account, we can't easily share the access. You can ask us to take the necessary screenshots, or you can take screenshots from your personal Cloudinary account.

## Long-term solution

Yes, I agree that we should update the CONTRIBUTING.md & the CONTRIBUTING_ID.md files accordingly.

**Comment by dekwahdimas** [comment]
Okay, now I feel embarrassed for requesting this, haha.

Can I contact you from discord, Mas @zainfathoni? I just found it after looking at your GitHub profile when searching for your email.

**Comment by zainfathoni** [comment]
Yes, of course. See you on Discord. 😉

**Comment by resir014** [comment]
Hi @dekwahdimas, I'm closing this as a duplicate and merging this issue with #639.

For the time being, as mentioned by @zainfathoni, the only way to gain these credentials is to ask either of us. And do take note that for security reasons, we only provide these credentials to those who, really, really, *really* need it.
